#!/usr/bin/env python3
"""Regenerates Sources/Aloud/Synthesis/ModelManifest.swift.

Run after changing the pinned revision, the voice list or the FluidAudio
version:

1. Delete ~/.cache/fluidaudio/Models, launch Aloud once so it downloads
   everything, then quit it. (The new manifest check fails on this run;
   that is expected.)
2. scripts/model-manifest.py <revision>

Every downloaded file is checked against the Hugging Face tree at
<revision> (LFS SHA-256 or git blob hash) before it goes into the manifest.
Voice .bin files are converted locally by FluidAudio from the repo's voice
data, so they have no repo counterpart; their local hash is used as is.
"""
import hashlib
import json
import os
import subprocess
import sys

REPO = "FluidInference/kokoro-82m-coreml"
CACHE = os.path.expanduser("~/.cache/fluidaudio/Models")
# Local cache folder -> path prefix inside the repo.
ROOTS = {"kokoro-82m-coreml/ANE": "ANE/", "kokoro": ""}
OUTPUT = os.path.join(os.path.dirname(__file__), "..", "Sources/Aloud/Synthesis/ModelManifest.swift")

revision = sys.argv[1]
tree = json.loads(subprocess.run(
    ["curl", "-sf", f"https://huggingface.co/api/models/{REPO}/tree/{revision}?recursive=true"],
    check=True, capture_output=True,
).stdout)
remote = {item["path"]: item for item in tree if item["type"] == "file"}

entries = []
for local_root, prefix in ROOTS.items():
    root = os.path.join(CACHE, local_root)
    for dirpath, _, filenames in os.walk(root):
        for name in filenames:
            path = os.path.join(dirpath, name)
            relative = os.path.relpath(path, root)
            if name.startswith("."):
                continue  # FluidAudio's own bookkeeping, e.g. .fluidaudio-revision
            data = open(path, "rb").read()
            sha256 = hashlib.sha256(data).hexdigest()
            item = remote.get(prefix + relative)
            if item is not None:
                blob = hashlib.sha1(b"blob %d\0" % len(data) + data).hexdigest()
                expected = item["lfs"]["oid"] if "lfs" in item else item["oid"]
                if expected not in (sha256, blob):
                    sys.exit(f"{local_root}/{relative} does not match {REPO}@{revision}")
            elif not (local_root.endswith("ANE") and name.endswith(".bin") and "/" not in relative):
                sys.exit(f"{local_root}/{relative} is not in {REPO}@{revision}")
            entries.append((f"{local_root}/{relative}", sha256))

lines = "\n".join(f'        ("{path}", "{sha}"),' for path, sha in sorted(entries))
with open(OUTPUT, "w") as out:
    out.write(f'''import Foundation
import CryptoKit
import FluidAudio

/// SHA-256 of every file Aloud's FluidAudio setup downloads into
/// ~/.cache/fluidaudio/Models, from `repo` at `revision`. FluidAudio only
/// pins the CoreML model chain to a revision; it fetches the pronunciation
/// files and voice packs from `main`. This check makes sure the files in use
/// are the reviewed ones either way. Generated by scripts/model-manifest.py.
enum ModelManifest {{
    static let repo = "{REPO}"
    static let revision = "{revision}"

    static let files: [(path: String, sha256: String)] = [
{lines}
    ]

    /// The files that are missing or don't match. Reads ~130MB, so call it
    /// off the main actor.
    static func mismatchedFiles() throws -> [URL] {{
        let models = try TtsCacheDirectory.ensure().appendingPathComponent("Models")
        return files.compactMap {{ file in
            let url = models.appendingPathComponent(file.path)
            guard let data = try? Data(contentsOf: url, options: .alwaysMapped) else {{ return url }}
            let digest = SHA256.hash(data: data).map {{ String(format: "%02x", $0) }}.joined()
            return digest == file.sha256 ? nil : url
        }}
    }}
}}
''')
print(f"Wrote {len(entries)} entries to {os.path.normpath(OUTPUT)}")
